export const notificationStyles = `
.nt-view,.nt-floating{font-family:inherit;color:var(--dsw-alias-label-primary,#202d32);font-size:14px;line-height:1.5}
.nt-view{max-width:1040px;margin:auto;padding:20px}.nt-view *{box-sizing:border-box}.nt-view h2,.nt-view h3,.nt-view h4{margin:0 0 8px}.nt-view p{margin:8px 0 14px}.nt-view small{color:var(--dsw-alias-label-secondary,#64757c)}
.nt-view button,.nt-popover-controls button{border:1px solid var(--dsw-alias-border-l1,#d4dfe0);border-radius:8px;background:var(--dsw-alias-bg-base,#fff);color:inherit;padding:7px 12px;font:inherit;cursor:pointer}.nt-view button:hover,.nt-popover-controls button:hover{background:var(--dsw-alias-bg-layer-2,#edf4f3)}.nt-view button:disabled{opacity:.5;cursor:default}.nt-view button[data-primary]{background:#17665c;color:white;border-color:#17665c}
.nt-header,.nt-row{display:flex;align-items:center;justify-content:space-between;gap:12px}.nt-header{align-items:flex-start;margin-bottom:20px}.nt-count{background:#e1efeb;color:#17665c;border-radius:14px;padding:2px 9px;font-size:14px;vertical-align:middle}
.nt-view input:not([type=checkbox]),.nt-view textarea,.nt-view select{display:block;width:100%;border:1px solid var(--dsw-alias-border-l1,#cbd7d9);border-radius:7px;background:var(--dsw-alias-bg-base,#fff);color:inherit;padding:9px 10px;font:inherit}.nt-view textarea{resize:vertical}.nt-view label{display:block;margin:10px 0}.nt-view .nt-check{display:flex;align-items:center;gap:7px;white-space:normal}.nt-view input[type=checkbox]{accent-color:#17665c;width:16px;height:16px;flex-shrink:0}
.nt-toolbar{display:flex;flex-wrap:wrap;align-items:center;gap:14px;margin:18px 0 12px}.nt-toolbar>input{flex:1;min-width:150px}.nt-toolbar label{margin:0}.nt-list{margin:14px 0}.nt-view .nt-item{display:flex;gap:12px;width:100%;border:0;border-bottom:1px solid var(--dsw-alias-border-l1,#e0e7e8);border-radius:0;padding:17px 8px;text-align:left;background:transparent}.nt-item>span:last-child{min-width:0}.nt-item strong,.nt-item small,.nt-item time{display:block;overflow-wrap:anywhere}.nt-item small{margin:4px 0}.nt-item time{font-size:11px;color:var(--dsw-alias-label-secondary,#6d7f85)}.nt-dot{flex:none;width:8px;height:8px;background:#168779;border-radius:50%;margin-top:6px}.nt-read{background:transparent;border:1px solid #b8c5c7}
.nt-detail,.nt-compose{border:1px solid var(--dsw-alias-border-l1,#ccdcd8);border-radius:12px;padding:20px;margin:16px 0;background:var(--dsw-alias-bg-layer-1,#f7faf9)}.nt-content{white-space:pre-wrap;overflow-wrap:anywhere}.nt-view fieldset{border:1px solid var(--dsw-alias-border-l1,#d7e1e1);border-radius:8px;margin:14px 0;padding:10px 14px}.nt-view legend{padding:0 6px}.nt-view footer{display:flex;flex-wrap:wrap;gap:8px;margin-top:16px}.nt-plan{padding:14px;border-left:3px solid #288577;background:var(--dsw-alias-bg-base,#fff);margin:16px 0}.nt-plan ul{padding-left:18px}.nt-plan li{margin-bottom:8px;overflow-wrap:anywhere}
.nt-asset{border:1px solid var(--dsw-alias-border-l1,#d7e1e1);border-radius:9px;padding:12px;margin:12px 0}.nt-asset>small{display:block}.nt-asset details{font-size:11px;margin:6px 0;overflow-wrap:anywhere}.nt-asset img,.nt-asset video{display:block;max-width:100%;max-height:300px;object-fit:contain;margin:12px auto}.nt-asset audio{width:100%;margin:12px 0}.nt-asset pre{max-height:240px;overflow:auto;white-space:pre-wrap}.nt-attachment-row{display:flex;justify-content:space-between;gap:8px;margin:10px 0;overflow-wrap:anywhere}.nt-receipts{padding-left:20px}.nt-receipts li{margin:10px 0}.nt-maintenance{margin-top:30px;color:var(--dsw-alias-label-secondary,#64757c)}.nt-empty{text-align:center;padding:28px 12px;color:var(--dsw-alias-label-secondary,#718287)}.nt-view [role=alert]{padding:12px;border:1px solid #ecc2b6;background:#fff2ed;color:#8a3929;border-radius:8px;overflow-wrap:anywhere}
.nt-bell{position:fixed;z-index:70;touch-action:none;user-select:none;display:grid;place-items:center;width:48px;height:48px;border:1px solid #b3d4cc;border-radius:50%;background:#f6fffb;color:#17665c;box-shadow:0 4px 18px #183b3326;cursor:pointer}.nt-bell>span{position:absolute;right:-4px;top:-4px;min-width:20px;padding:1px 5px;border-radius:10px;background:#d05538;color:#fff;font-size:11px;font-weight:650}.nt-popover{position:fixed;z-index:80;top:70px;bottom:24px;width:440px;max-width:calc(100vw - 32px);overflow:auto;overscroll-behavior:contain;border:1px solid var(--dsw-alias-border-l1,#c9d9d5);border-radius:15px;background:var(--dsw-alias-bg-base,#fff);box-shadow:0 14px 60px #182e3330}.nt-popover-controls{position:sticky;top:0;z-index:3;background:var(--dsw-alias-bg-base,#fff);display:flex;justify-content:space-between;padding:10px 14px 0}.nt-compact{padding:14px}.nt-compact .nt-header{margin:8px 0 14px;align-items:center}.nt-compact h2{font-size:18px}.nt-compact .nt-detail,.nt-compact .nt-compose{padding:12px}.nt-compact .nt-toolbar{gap:8px}.nt-popover button:focus-visible,.nt-bell:focus-visible,.nt-view button:focus-visible{outline:3px solid #68b8a8;outline-offset:2px}
@media(max-width:600px){.nt-view{padding:12px}.nt-header{flex-wrap:wrap}.nt-toolbar>input{flex-basis:100%}.nt-detail,.nt-compose{padding:12px}.nt-popover{top:12px;bottom:12px}.nt-compact .nt-header{flex-wrap:nowrap}}
`
